server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JustForAPromise/config/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/